## 예외처리
### 프로그램 오류
프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우가 있다.
이러한 결과를 초래하는 원인을 프로그램 에러 또는 오류라고 한다.
```
컴파일 에러 : 컴파일 시에 발생하는 에러
런타임 에러 : 실행 시에 발생하는 에러
논리적 에러 : 실행은 되지만, 의도와 다르게 동작하는 것
```
자바에서 실행 시(Runtime) 발생할 수 있는 프로그램 오류를 에러와 예외. 두가지로 구분한다.
```
에러는 메모리부족이나 스택오버플로우와 같이 일단 발생하면 복구할 수 없는 심각한 오류 
예외는 발생하더라도 수습될 수 있는 비교적 덜 심각한 것이다.
```
그래서 에러가 발생하면, 프로그램의 비정상적인 종료를 막을 길이 없지만, 예외는 발생하더라도 적절한 코드를 미리 작성해 놓음으로써 프로그램의 비정상적인 종료를 막을수 있다.

### 예외처리하기 - try-catch문
예외 처리란 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성한 것이며, 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 종료를 막고, 실행상태를 유지할 수 있도록 하는것이다.

```
예외처리의 정의
    프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
예외처리의 목적
    프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는것
```
발생한 예외를 처리하지 못하면, 프로그램은 종료되며, 처리되지 못한 예외는 JVM의 예외처러기가 받아서 원인을 화면에 출력한다.

```java
try {
	// 예외가 발생할 가능성이 있는 문장
} catch (Exception1 e1) {
	// 예외가 발생했을 경우 처리하기 위한 문장
} catch (Exception2 e2) {
	// 예외가 발생했을 경우 처리하기 위한 문장
}
```

### try-catch문의 흐름
```
try블럭 내에서 예외가 발생한 경우.
    발생한 예외와 일치하는 catch블럭이 있는지 확인
    일치하는 catch블럭을 찾게되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그다음 문장을 수행. 
    만일 찾지 못하면 예외는 처리되지 못함.
    
try블럭 내에서 예외가 발생하지 않은 경우
    catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.
````

---

#### printStackTrace()와 getMessage()
예외가 발생햇을 때 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨있으며, printStackTrace()와 getMessage()를 통해서 이 정보들을 얻을수 있다.
```
printStackTrace()
    예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
getMessage()
    발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
```

#### 멀티 catch블럭
JDK1.7부터 여러 catch블럭을 '|'기호를 이용해서 하나의 catch블럭으로 합칠 수 있게 되었으며, 이를 멀티 catch블럭이라 한다.
```멀티 catch블럭의 '|'는 논리 연산자가 아니라 기호이다.```

```java
try {
	//
} catch ( ExceptionA | ExceptionB e) {
	e.printStackTrace();
}
```
만약 멀티 catch블럭의 '|'와 연결된 예외 클래스가 부모와 자식관계라면 컴파일 에러가 발생한다.
왜냐하면 부모와 자식 관계에 있다면 그냥 부모클래스만 써주면 똑같기때문이다.

### 메서드에 예외 선언하기
메서드에 예외를 선언하려면 메서드의 선언부에 키워드 throw를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어주면 된다.

```java
void method() throws Exception1, Exception2, Exception...{
	//
}
```
메서드의 선언부에 예외를 선언함으로써 메서드를 사용하려는 사람이 메서드의 선언부를 보았을 때, 이 메서드를 사용하기 위해서는 어떠한 예외들이 처리되어져야 하는지 쉽게 알 수 있다.

**예외를 메서드의 throws에 명시하는 것은 예외를 처리하는 것이 아니라, 자신을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것이다.**
예외를 전달받은 메서드가 또다시 자신을 호출한 메서드에게 전달할 수 있으며, 이런식으로 계속 호출스택에 있는 메서드들을 따라 전달되다가 마지막에 있는 main메서드에서도 처리되지않으면 프로그램이 종료된다.

### finally 블럭
finally블럭은 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용된다.
try-catch문의 끝에 선택적으로 덧붙여 사용할 수 있으며, try-catch-finally의 순서로 구성된다.
```java
    try {
		//예외가 발생할 가능성있는 문장
    } catch ( Exception1 e1) {
    	// 예외처리를 위한 문장
    } finally {
    	// 예외 발생여부에 관계없는 무조건 실행할 문장
    }
```
예외가 발생한 경우에는 try-catch-finally순으로 실행
그렇지 않은 경우에는 try-finally순으로 실행



